Sos 453 agent for algernon
StartupOS/verinfast pull request #2
Opened 2023-07-05 18:20 UTC by aylusltd

It's not there yet but putting this on your radar.

2023-07-06 14:51 UTC, aylusltd commented
Finished

2023-07-07 15:56 UTC, SeanTConrad requested changes

2023-07-07 15:56 UTC, SeanTConrad commented on verinfast/cloud/aws.py
> -
This file needs to be moved on my machine, or it breaks the import of things in the aws path.

2023-07-07 15:56 UTC, SeanTConrad commented on verinfast/agent.py
>  from cloud.aws import runAws
I would change to `from cloud.aws.aws` import runAws

2023-07-07 15:56 UTC, SeanTConrad commented on verinfast/cloud/aws/instances.py
> +import regions as r
On my machine, this needs to be:
`import cloud.aws.regions as r`
Only the parent script that is run has its path in the sys path.

2023-07-07 15:56 UTC, SeanTConrad commented on verinfast/cloud/gcp/instances.py
> +from zones import zones
Probably needs to be:
`import cloud.gcp.zones as zones`

2023-07-07 16:10 UTC, SeanTConrad commented on verinfast/agent.py
> +            aws_instance_file = get_aws_instances(accountId=provider["acconut"], path_to_output=output_dir)
"acconut" should be "account"

2023-07-07 18:44 UTC, SeanTConrad approved these changes

2023-07-07 18:44 UTC, merged